<?php

use Illuminate\Database\Seeder;

class InfluencersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('influencers')->delete();
        
        \DB::table('influencers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'job_position_id' => 0,
                'political_position_id' => '',
                'political_party_id' => 0,
                'country_id' => '',
                'state_id' => 0,
                'city_id' => 0,
                'screen_name' => 'miputotuit',
                'name' => 'miputotuit',
                'twitter_id' => '1037045468075880448',
                'twitter_screen_name' => 'miputotuit',
                'twitter_name' => 'miputotuit',
                'twitter_description' => 'Pasaba por acá y ya. Que gonorrea ese twitter.',
                'twitter_personal_url' => NULL,
                'twitter_url' => 'https://twitter.com/miputotuit',
                'twitter_followers_count' => 19,
                'twitter_friends_count' => 271,
                'twitter_statuses_count' => 74,
                'twitter_image_normal_url' => 'https://pbs.twimg.com/profile_images/1037666165898846208/60bhSQJ2_normal.jpg',
                'twitter_image_url' => 'https://pbs.twimg.com/profile_images/1037666165898846208/60bhSQJ2.jpg',
                'active' => 1,
                'created_at' => '2018-09-10 20:03:13',
                'updated_at' => '2018-09-10 20:03:13',
            ),
            1 => 
            array (
                'id' => 2,
                'job_position_id' => 0,
                'political_position_id' => '',
                'political_party_id' => 0,
                'country_id' => '',
                'state_id' => 0,
                'city_id' => 0,
                'screen_name' => 'AlvaroUribeVel',
                'name' => 'Álvaro Uribe Vélez',
                'twitter_id' => '61097151',
                'twitter_screen_name' => 'AlvaroUribeVel',
                'twitter_name' => 'Álvaro Uribe Vélez',
                'twitter_description' => 'Bienvenidos a la cuenta oficial de Twitter de Álvaro Uribe Vélez. Presidente de la República de Colombia 2002-2010. Página Web.',
                'twitter_personal_url' => 'https://t.co/IrqMq4a3cJ',
                'twitter_url' => 'https://twitter.com/AlvaroUribeVel',
                'twitter_followers_count' => 4764626,
                'twitter_friends_count' => 2275,
                'twitter_statuses_count' => 70733,
                'twitter_image_normal_url' => 'https://pbs.twimg.com/profile_images/479052171837984768/mlO43FWa_normal.jpeg',
                'twitter_image_url' => 'https://pbs.twimg.com/profile_images/479052171837984768/mlO43FWa.jpeg',
                'active' => 1,
                'created_at' => '2018-09-10 20:18:14',
                'updated_at' => '2018-09-10 20:18:14',
            ),
            2 => 
            array (
                'id' => 3,
                'job_position_id' => 0,
                'political_position_id' => '',
                'political_party_id' => 0,
                'country_id' => '',
                'state_id' => 0,
                'city_id' => 0,
                'screen_name' => 'IvanDuque',
                'name' => 'Iván Duque',
                'twitter_id' => '77653794',
                'twitter_screen_name' => 'IvanDuque',
                'twitter_name' => 'Iván Duque',
                'twitter_description' => 'Presidente de la República de Colombia 🇨🇴 2018-2022. Legalidad, Emprendimiento y Equidad. https://t.co/LSGyNuHWTQ',
                'twitter_personal_url' => NULL,
                'twitter_url' => 'https://twitter.com/IvanDuque',
                'twitter_followers_count' => 602526,
                'twitter_friends_count' => 2464,
                'twitter_statuses_count' => 22460,
                'twitter_image_normal_url' => 'https://pbs.twimg.com/profile_images/1002248730832261120/4QZIKUGo_normal.jpg',
                'twitter_image_url' => 'https://pbs.twimg.com/profile_images/1002248730832261120/4QZIKUGo.jpg',
                'active' => 1,
                'created_at' => '2018-09-10 20:21:09',
                'updated_at' => '2018-09-10 20:21:09',
            ),
            3 => 
            array (
                'id' => 4,
                'job_position_id' => 0,
                'political_position_id' => '',
                'political_party_id' => 0,
                'country_id' => '',
                'state_id' => 0,
                'city_id' => 0,
                'screen_name' => 'MinjusticiaCo',
                'name' => 'MinJusticia Colombia',
                'twitter_id' => '478892632',
                'twitter_screen_name' => 'MinjusticiaCo',
                'twitter_name' => 'MinJusticia Colombia',
                'twitter_description' => 'Noticias y actividades del Ministerio de Justicia y del Derecho de Colombia',
                'twitter_personal_url' => 'https://t.co/o7XOCkN8e3',
                'twitter_url' => 'https://twitter.com/MinjusticiaCo',
                'twitter_followers_count' => 256814,
                'twitter_friends_count' => 3169,
                'twitter_statuses_count' => 44873,
                'twitter_image_normal_url' => 'https://pbs.twimg.com/profile_images/1030098783147831296/dZVqTvPz_normal.jpg',
                'twitter_image_url' => 'https://pbs.twimg.com/profile_images/1030098783147831296/dZVqTvPz.jpg',
                'active' => 1,
                'created_at' => '2018-09-10 20:39:39',
                'updated_at' => '2018-09-10 20:39:39',
            ),
            4 => 
            array (
                'id' => 9,
                'job_position_id' => 0,
                'political_position_id' => '',
                'political_party_id' => 0,
                'country_id' => '',
                'state_id' => 0,
                'city_id' => 0,
                'screen_name' => 'EnriquePenalosa',
                'name' => 'Enrique Peñalosa',
                'twitter_id' => '108717093',
                'twitter_screen_name' => 'EnriquePenalosa',
                'twitter_name' => 'Enrique Peñalosa',
                'twitter_description' => 'Alcalde Mayor de Bogotá D.C. 2016 - 2019 Instagram: https://t.co/iaqnIrKYXZ',
                'twitter_personal_url' => 'https://t.co/SOX8n0ODGF',
                'twitter_url' => 'https://twitter.com/EnriquePenalosa',
                'twitter_followers_count' => 1849044,
                'twitter_friends_count' => 850,
                'twitter_statuses_count' => 19633,
                'twitter_image_normal_url' => 'https://pbs.twimg.com/profile_images/807285259242979328/EAOQNvnR_normal.jpg',
                'twitter_image_url' => 'https://pbs.twimg.com/profile_images/807285259242979328/EAOQNvnR.jpg',
                'active' => 1,
                'created_at' => '2018-09-10 21:14:28',
                'updated_at' => '2018-09-10 21:14:28',
            ),
            5 => 
            array (
                'id' => 10,
                'job_position_id' => 0,
                'political_position_id' => '',
                'political_party_id' => 0,
                'country_id' => '',
                'state_id' => 0,
                'city_id' => 0,
                'screen_name' => 'RoyBarreras',
                'name' => 'Roy Barreras U1',
                'twitter_id' => '62154340',
                'twitter_screen_name' => 'RoyBarreras',
                'twitter_name' => 'Roy Barreras U1',
                'twitter_description' => 'Senador de la República Presidente de la Comisión de Paz del Senado Cuenta oficial https://t.co/rLd17OOQ7Z',
                'twitter_personal_url' => 'https://t.co/xDuAJcNc1n',
                'twitter_url' => 'https://twitter.com/RoyBarreras',
                'twitter_followers_count' => 64258,
                'twitter_friends_count' => 1118,
                'twitter_statuses_count' => 7172,
                'twitter_image_normal_url' => 'https://pbs.twimg.com/profile_images/1031921082834591744/_Fb_VlUG_normal.jpg',
                'twitter_image_url' => 'https://pbs.twimg.com/profile_images/1031921082834591744/_Fb_VlUG.jpg',
                'active' => 1,
                'created_at' => '2018-09-10 21:22:36',
                'updated_at' => '2018-09-10 21:22:36',
            ),
            6 => 
            array (
                'id' => 11,
                'job_position_id' => 0,
                'political_position_id' => '',
                'political_party_id' => 0,
                'country_id' => '',
                'state_id' => 0,
                'city_id' => 0,
                'screen_name' => 'petrogustavo',
                'name' => 'Gustavo Petro',
                'twitter_id' => '49849732',
                'twitter_screen_name' => 'petrogustavo',
                'twitter_name' => 'Gustavo Petro',
                'twitter_description' => 'Perfil Oficial del dirigente político progresista colombiano Gustavo Petro. Por una Colombia Humana con justicia social y en Paz',
                'twitter_personal_url' => 'https://t.co/ho5XWkfwTr',
                'twitter_url' => 'https://twitter.com/petrogustavo',
                'twitter_followers_count' => 3272315,
                'twitter_friends_count' => 2171,
                'twitter_statuses_count' => 106598,
                'twitter_image_normal_url' => 'https://pbs.twimg.com/profile_images/962471262747529216/Uo8lOkRJ_normal.jpg',
                'twitter_image_url' => 'https://pbs.twimg.com/profile_images/962471262747529216/Uo8lOkRJ.jpg',
                'active' => 1,
                'created_at' => '2018-09-10 22:05:08',
                'updated_at' => '2018-09-10 22:05:08',
            ),
        ));
        
        
    }
}