php artisan iseed cities --force
php artisan iseed countries --force
php artisan iseed influencers --force
php artisan iseed job_positions --force
php artisan iseed political_parties --force
php artisan iseed political_positions --force
php artisan iseed states --force
php artisan iseed users --force
php artisan iseed work_areas --force
